version: "3"
services:
  app:
    image: sveltekit:node
    ports:
      - "3000:3000"
    environment:
      - MONGO_USER=user
      - MONGO_PW=password8374
      - MONGO_URL=db
      - MONGO_URI=user:password8374@mongodb
      - BODY_SIZE_LIMIT=50000000
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:7.0.5-ubuntu2204
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=password8374
    volumes:
      - type: bind
        source: ./data
        target: /data/db
